# Generated by Django 4.0.4 on 2022-05-21 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('DNI', models.CharField(max_length=8, unique=True)),
                ('birthDate', models.DateField()),
                ('sex', models.CharField(max_length=1)),
                ('password', models.CharField(max_length=20)),
                ('token', models.CharField(default='1111', max_length=4, null=True)),
                ('is_admin', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('covid_doses', models.IntegerField()),
                ('covid_date', models.DateField(null=True)),
                ('gripe', models.BooleanField()),
                ('gripe_date', models.DateField(null=True)),
                ('fiebreA', models.BooleanField()),
                ('fiebreA_date', models.DateField(null=True)),
                ('fiebreA_eleccion', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField()),
                ('date', models.DateField(null=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuApp.center')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuApp.vaccine')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacuApp.center'),
        ),
    ]
