# Generated by Django 4.0.4 on 2022-05-14 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=100)),
                ('DNI', models.CharField(max_length=8, unique=True)),
                ('sex', models.CharField(max_length=1)),
                ('password', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=4, null=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuApp.center')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuApp.center')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuApp.user')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuApp.vaccine')),
            ],
        ),
    ]
