# Generated by Django 4.0.4 on 2022-07-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacuApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='descripcion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='initialDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='observaciones',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.IntegerField(default=0),
        ),
    ]
