# Generated by Django 4.0.4 on 2022-06-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacuApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
