# Generated by Django 4.0.4 on 2022-05-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacuApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='User',
            name='birthDate',
            field=models.DateField(default="2000-01-01"),
            preserve_default=False,
        ),
    ]
