# Generated by Django 4.0.4 on 2022-05-18 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacuApp', '0002_user_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('covid_1', models.BooleanField()),
                ('covid_2', models.BooleanField()),
                ('gripe', models.BooleanField()),
                ('fiebreA', models.BooleanField()),
                ('fiebreA_eleccion', models.BooleanField()),
                ('name', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vacuApp.user')),
            ],
        ),
    ]
