# Generated by Django 4.0.4 on 2022-06-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacuApp', '0002_alter_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='descripcion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='observaciones',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
