# Generated by Django 4.0.4 on 2022-07-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacuApp', '0003_appointment_descripcion_appointment_observaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
