# Generated by Django 4.0.4 on 2022-05-18 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacuApp', '0003_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vacuApp.center'),
        ),
    ]
