# Generated by Django 4.0.4 on 2022-07-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacuApp', '0004_appointment_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='edad',
            field=models.IntegerField(null=True),
        ),
    ]
