# Generated by Django 4.0.4 on 2022-07-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacuApp', '0005_appointment_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
