# Generated by Django 4.0.4 on 2022-07-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacuApp', '0006_user_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.IntegerField(default=None),
        ),
    ]
