# Generated by Django 4.0.4 on 2022-07-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacuApp', '0006_user_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='initialDate',
            field=models.DateField(null=True),
        ),
    ]
