# Generated by Django 4.0.4 on 2022-07-10 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacuApp', '0007_alter_user_telefono'),
        ('vacuApp', '0007_appointment_initialdate'),
    ]

    operations = [
    ]
