# Generated by Django 4.0.4 on 2022-07-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacuApp', '0007_alter_user_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='initialDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.IntegerField(default=0),
        ),
    ]
