# Generated by Django 4.0.4 on 2022-05-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacuApp', '0008_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='name',
        ),
    ]
