# Generated by Django 4.0.4 on 2022-07-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacuApp', '0008_merge_20220710_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.IntegerField(default=0),
        ),
    ]
