# Generated by Django 4.0.4 on 2022-05-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacuApp', '0011_alter_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='covid_doses',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='state',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='covid_doses',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='covid_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='fiebreA_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='gripe_date',
            field=models.DateField(null=True),
        ),
    ]
