# Generated by Django 4.0.4 on 2022-05-20 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacuApp', '0012_remove_history_covid_1_remove_history_covid_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacuApp.center'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
